### ISSUE TITLE
installation?

### ISSUE THREAD

**Issue by bitelxux** [veksh/netdata-numsessions#1]
Hi, I have copied logins.chart.py to /usr/libexec/netdata/python.d and logins.conf to /etc/netdata/python.d
After restarting netdata I can't find it on the default netdata dashboard. Is there any thing I'm missing?

Running netdata container. Netdata versioon:  netdata 1.8.0-613-g9563e10_rolling

Thanks !

**Comment by veksh** [comment]
I've tested this plugin only with netdata 1.10, mostly on centos. Maybe some python modules are
missed in your installation? Recent netdata prefer python 3.x.

To see some debug output (and maybe a reason why plugin is disabled), try running it [manually](https://github.com/firehol/netdata/wiki/Add-more-charts-to-netdata) like

```
sudo su -s /bin/bash netdata
/usr/libexec/netdata/plugins.d/python.d.plugin 1 debug trace logins
```

**Comment by bitelxux** [comment]
Hi, thanks for answering !

I finally found why it was failing ( as you have proposed, running it manually )

The line users = raw_data[0].split(',')[1].split(' ')[2] is cutting a string from the output of uptime with up hours and minutes instead the number of users, for example, if uptime is 

15:15:21 up 17 days,  1:46,  0 users,  load average: 1.33, 1.32, 1.46

That string will be "1:46"

And it happens that netdata is expecting a number.

uptime version uptime from procps-ng 3.3.10

May I suggest to use a regular expression to properly get the users instead of splitting?

Thank you again.

**Comment by veksh** [comment]
Ok, I've switched parsing uptime to (less position-dependent) regexp; please check it now.
